blog/urls.py
from blog import views
from django.urls import path
urlpatterns = [
    path('', views.home, name="home"),
    path('contact/', views.contact, name="contact"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('profile/', views.profile, name="profile"),
    path('signup/', views.user_signup, name="signup"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('post-add/', views.post_add, name="post_add"),
    path('post-update/<int:id>/', views.post_update, name="post_update"),
    path('post-delete/<int:id>/', views.post_delete, name="post_delete"),
]

miniblog2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.db.models.base import Model

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=150)
    desc = models.TextField()

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import fields, widgets
from blog import models
from blog.models import Post
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm,UsernameField
from django.contrib.auth.models import User
from django.utils.translation import gettext, gettext_lazy as _


class User_Signup(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control'}),
            'first_name': forms.TextInput(attrs={'class':'form-control'}),
            'last_name': forms.TextInput(attrs={'class':'form-control'}),
            'email': forms.TextInput(attrs={'class':'form-control'}),
        }

class User_Login(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'autofocus':True, 'class':'form-control'}))
    password = forms.CharField(label=_('Password'), strip=False, widget=forms.PasswordInput(attrs={'autocomplete':'current-password', 'class':'form-control'}))

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'desc']
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control'}),
            'desc': forms.Textarea(attrs={'class':'form-control'}),
        }

blog/views.py
from django.contrib.auth import authenticate
from django.http.response import HttpResponseRedirect
from django.shortcuts import render 
from blog.forms import User_Signup, User_Login, PostForm
from django.contrib.auth.models import Group
from django.contrib.auth import authenticate,login, logout
from blog.models import Post
from django.contrib import messages
# Create your views here.

def home(request):
    posts = Post.objects.all()
    return render(request, "blog/home.html",{'posts':posts})

def contact(request):
    return render(request, "blog/contact.html")

def user_signup(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            fm = User_Signup(request.POST)
            if fm.is_valid():
                user = fm.save()
                group = Group.objects.get(name="Autho")
                user.groups.add(group)
                messages.success(request, "Congratulations! You have become an Author")                
                return HttpResponseRedirect('/signup/')
        else:
            fm = User_Signup()
        return render(request, "blog/signup.html", {'form':fm})
    else:
        return HttpResponseRedirect('/dashboard/')

def profile(request):
    if request.user.is_authenticated:
        user = request.user
        uname = user.username
        fname = user.first_name
        lname = user.last_name
        email = user.email
        groups = groups = user.groups.all()
        context = {
            'uname':uname,
            'fname':fname,
            'lname':lname,
            'email':email,
            'groups':groups,
        }
        return render(request,'blog/profile.html',context)
    else:
        return HttpResponseRedirect('/login/')

def user_login(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            fm = User_Login(request = request, data=request.POST)
            if fm.is_valid():
                uname = fm.cleaned_data['username']
                upass = fm.cleaned_data['password']
                user = authenticate(username=uname, password=upass)
                if user is not None:
                    login(request, user)
                    messages.success(request, "Login Successfully!")
                    return HttpResponseRedirect('/dashboard/')
        else:
            fm = User_Login()
        return render(request,'blog/login.html', {'form':fm})
    else:
        return HttpResponseRedirect('/dashboard/')

def user_logout(request):
    if request.user.is_authenticated:
        logout(request)
        return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/login/')

def dashboard(request):    
    if request.user.is_authenticated:
        posts = Post.objects.all()
        user = request.user
        full_name = user.get_full_name()
        groups = user.groups.all() 
        context = {
            'posts':posts,
            'full_name':full_name,
            'groups':groups
        }
        return render(request,'blog/dashboard.html',context)
    else:
        return HttpResponseRedirect('/login/')
        
def post_add(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            form = PostForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, "Post Added Successfully!")
                return HttpResponseRedirect('/post-add/')
        else:
            form = PostForm()
        return render(request,'blog/post_add.html',{'form':form})
    else:
        return HttpResponseRedirect('/login/')

def post_update(request, id):
    if request.user.is_authenticated:
        if request.method == "POST":
            post = Post.objects.get(pk=id)
            form = PostForm(request.POST, instance=post)
            if form.is_valid():
                form.save()
                messages.success(request, "Post Update Successfully!")
                return HttpResponseRedirect('/dashboard/')
        else:
            post = Post.objects.get(pk=id)
            form = PostForm(instance=post)
        return render(request,'blog/post_update.html',{'form':form})
    else:
        return HttpResponseRedirect('/login/')

def post_delete(request, id):
    if request.user.is_authenticated:
        if request.method == "POST":
            post = Post.objects.get(pk=id)
            post.delete()
            return HttpResponseRedirect('/dashboard/')
    else:
        return HttpResponseRedirect('/login/')

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
    <title>Blog App</title>
</head>
<body>
    {% include 'blog/navbar.html' %}
    
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% block messages %}
                {% endblock messages %}
            </div>
        </div>

        <div class="row">
                {% block side %}
                {% endblock side %}
             
                {% block content %}
                {% endblock content %}
        </div>

    </div>    
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/contact.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="col-sm-12 my-5">
        <form>
            <div class="row">
                <div class="form-group col-sm-6">
                    <label for="name">Name: </label>
                    <input type="text" class="form-control" id="name" placeholder="Enter Name">
                </div>
                <div class="form-group col-sm-6">
                    <label for="email">Email: </label>
                    <input type="email" class="form-control" id="email" placeholder="Enter email">
                </div>    
            </div>
            <div class="form-group">
                <label for="address">Address: </label>
                <input type="text" class="form-control" id="address" placeholder="Enter Address">
            </div>
            <div class="form-group">
                <label for="message">Message: </label>
                <textarea type="text-area" rows="4" class="form-control" id="message" placeholder="Enter email"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
            </form>
    </div>
{% endblock content %}

blog/templates/blog/dashboard.html
{% extends 'blog/base.html' %}

{% block messages %}
    {% if messages %}
        {% for msg in messages %}
            <div {% if msg.tags %} class="alert alert-{{msg.tags}} alert-dismissible fade show text-center" {% endif %} >{{msg}}</div>
        {% endfor %}
    {% endif %}
{% endblock messages %}

{% block side %}
    <div class="col-sm-2 py-5 ">
        <div class="text-center">
            <h3 class="py-5">Profile</h3>
            <h5>{{full_name}}</h5>
            {% for group in groups %}
                <h5>{{group}}</h5>
            {% endfor %}
        </div>
    </div>
{% endblock side %}
    
{% block content %}
    <div class="col-sm-10 my-5">
        <h1 class="mb-5">Dashboard</h1>
        <a href="{% url 'post_add' %}" class="btn btn-success">Add Post</a>
        <h4 class="alert alert-info my-3 text-center">Show Post Information</h4>
        
        {% if posts %}
        <table class="table table-striped table-dark table-hover">
            <thead>
                <tr>
                <th scope="col">ID</th>
                <th scope="col">Title</th>
                <th scope="col">Description</th>
                <th scope="col">Actions</th>
                </tr>
            </thead>
                {% for post in posts %}
                    <tbody>
                        <tr>
                        <th scope="row">{{post.id}}</th>
                        <td>{{post.title}}</td>
                        <td class="text-justify">{{post.desc}}</td>
                        <td>
                            <a href="{% url 'post_update' post.id %}" class="btn btn-warning btn-sm" >Update</a>
                            {% if perms.blog.delete_post %}
                                <form action="{% url 'post_delete' post.id %}" method="POST" class="d-inline" style="display: inline;">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger btn-sm mt-2" >Delete</button>
                                </form>
                            {% endif %}
                        </td>
                        </tr>
                    </tbody>
                {% endfor %}
            {% else %}
                <div class="jumbotron jumbotron-fluid jumbo-color my-5">
                    <div class="container">
                        <h3 class="display-4 font-weight-bold">No Post Available</h3>
                    </div>
                </div>
        {% endif %}
        </table>
    </div>
{% endblock content %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}


{% block content %}
    <div class="col-sm-12">
        <h2 class="mt-5">Home Page</h2>
        
        {% if posts %}
            {% for post in posts %}
                <div class="jumbotron jumbotron-fluid jumbo-color my-5">
                    <div class="container">
                        <h3 class="display-5 font-weight-bold">{{post.title}}</h3>
                        <p class="lead text-justify">{{post.desc}}</p>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="jumbotron jumbotron-fluid jumbo-color my-5">
                <div class="container">
                    <h3 class="display-4 font-weight-bold">No Post Available</h3>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock content %}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="col-sm-12">
        <h2 class="py-5">Login</h2>
        <form action="" method="POST" novalidate>
            {% csrf_token %}
            {% for fm in form %}
                {{fm.label_tag}} {{fm}} <span class="text-warning">{{fm.errors|striptags}}</span><br>
            {% endfor %}
            <button type="submit" class="btn btn-success">Login</button>
            
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <h4 class="alert alert-danger text-center my-5">{{error}}</h4>
                {% endfor %}
            {% endif %}
        </form>
    </div>
{% endblock content %}

blog/templates/blog/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand ml-5" style="margin-right: 55%" href="{% url 'home' %}">Mini Blog App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>

            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'profile' %}">Profile</a>
                </li>
            {% endif %}
            
            <li class="nav-item">
                <a class="nav-link" href="{% url 'contact' %}">Contact</a>
            </li>
            
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
                </li>
            {% endif %}

            {% if not request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signup' %}">Signup</a>
                </li>
            {% endif %}
            
            {% if not request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
            {% endif %}
            
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

blog/templates/blog/post_add.html
{% extends 'blog/base.html' %}


{% block messages %}
    {% if messages %}
        {% for msg in messages %}
            <p class="alert alert-{{msg.tags}} text-center">{{msg}}</p>
        {% endfor %}
    {% endif %}
{% endblock messages %}

{% block content %}
    <div class="col-sm-12 py-5">
        <h1 class="mb-5">Dashboard / Update Post</h1>
        <form action="" method="POST" novalidate class="d-inline">
            {% csrf_token %}
            {% for fm in form %}
                {{fm.label_tag}} {{fm}} <span class="text-warning">{{fm.errors|striptags}}</span><br>
            {% endfor %}
            <button class="btn btn-success">Add Post</button>
        </form>        
            <a href="{% url 'dashboard' %}" class="btn btn-warning">Back</a>
    </div>
{% endblock content %}

blog/templates/blog/post_update.html
{% extends 'blog/base.html' %}

{% block messages %}
    {% if messages %}
        {% for msg in messages %}
            <p class="alert alert-{{msg.tags}} text-center">{{msg}}</p>
        {% endfor %}
    {% endif %}
{% endblock messages %}

{% block content %}
    <div class="col-sm-12 py-5">
        <h1 class="mb-5">Dashboard / Add Post</h1>
        <form action="" method="POST" novalidate>
            {% csrf_token %}
            {% for fm in form %}
                {{fm.label_tag}} {{fm}} <span class="text-danger">{{fm.errors|striptags}}</span><br>
            {% endfor %}
            <button class="btn btn-success">Update Post</button>
        </form>        
    </div>
{% endblock content %}

blog/templates/blog/profile.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="col-sm-12">
        <h2 class="py-5">Profile</h2>
        <ul>
            <li><h3><pre class="text-white">Username:   {{uname}}</pre></h3></li>
            <li><h3><pre class="text-white">First Name: {{fname}}</pre></h3></li>
            <li><h3><pre class="text-white">Last Name:  {{lname}}</pre></h3></li>
            <li><h3><pre class="text-white">Email:      {{email}}</pre></h3></li>
            <li>
                {% for group in groups %}
                <h3><pre class="text-white">Group:      {{group}}</pre></h3>
                {% endfor %}
            </li>
        </ul>
    </div>
{% endblock content %}

blog/templates/blog/signup.html
{% extends 'blog/base.html' %}

{% block messages %}
    {% if messages %}
        {% for msg in messages %}
            <div {% if msg.tags %} class="alert alert-{{msg.tags}} text-center" {% endif %} >{{msg}}</div>
        {% endfor %}
    {% endif %}
{% endblock messages %}

{% block content %}
    <div class="col-sm-12">
        <h1 class="my-5">Become an Author</h1>
        <form action="" method="POST" novalidate>
            {% csrf_token %}
            {% for fm in form %}
                {{fm.label_tag}} {{fm}} <span class="text-warning">{{fm.errors|striptags}}</span><br>
            {% endfor %}
            <button class="btn btn-success mb-5">SignUp</button>
        </form>
    </div>
{% endblock content %}